apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: homework
  labels:
    app: httpd
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      nodeSelector:
        homework: "true"
      containers:
      - name: main-container
        image: busybox:stable
        command: ["sh", "-c", "httpd -f -p 8000"]
        workingDir: /homework
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: homework-volume
          mountPath: /homework
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -fv /homework/index.html"]
        readinessProbe:
          exec:
            command:
            - ls
            - /homework/index.html
      initContainers:
      - name: init-container
        image: busybox:stable
        volumeMounts:
        - name: homework-volume
          mountPath: /init
        command: ["/bin/sh", "-c"]
        args:
          - echo "<html><body>kubernetes-controllers</body></html>" > /init/index.html
      volumes:
      - name: homework-volume
        emptyDir: {}