apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
  namespace: homework
spec:
  storageClassName: "standard-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
